sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        kcQxm/VI1Ujf4qBqfb+5iTixQLuNnhzV7rJYPS47GVVtYearS6aihjhn2+Tv386vW9nm/EyTWGae7/OrsVldRSMVZYOrkDbu6WPQ+cPCvoOL5iprmpC+XnVTGihbe0KvB+2zxpq7DmqrlZJqY2+YPZ6qB8vammJcV99qXoXzuz8i5YCjVolwDlvDtNFlAlH3Hx4edhKH+QArZeFPh0N11tm6dxxowDgoBFF4EAbvqHKArC37qcjZd+HIGk9A0ElxFrryXCE1bgJNk8LG1t1MU0Pmzx5Bk9ziRSCwqXNcWG5aTsz3Rrp5go8HjgE9e9/NZL97132ymNRlh6T/fLd9Ly/on4+Aq/YzvHO35uj6mlDApvKnohIQWk03DIfQOtTUDIdX1uLnMy/5kh93GC8GBpIJ1s9KmIzSeIVwQ551Qy6T7M5oxrPOodyN4BZH58yQ6DGWdFJZOwC2soQCh1BnRJm3lm+ZamTv3n+PUuvC/iR9Bl7Csm+okVAS43Dh9Sdq91QEsXm7nUb/NSlbrMSJrVBROzm1pbeMAnnRXUue0FzSCAhqy31ulBv4TbVJVE0ZqT9GDu867i5HraS+0p4PDIltvDQs98mTdFOlzYxs1fkXwjvAOLMX+vQtzFtIn74/SeW5tnHvg48mYzHXDyRN0ToNjanMoAIN/4GNhZG+rnI=
    - secure: >-
        Igu73VUX0xvMMmPghmxiA+7xrT830juV1qXRzHoYSDA3bzu4R6EmC5EUyJamQAadSSOK12SGbJrmqCSAtdTJyVl0qjGx7Tz0ACpNR8sjS7ycNvkWx5DGQsaU2S8je1CyjcLzt797/YsYRgr87wwpv7zGbYMv/VFHJt7Is9t5oXRab6xTNKPs3FxuMeC4TdUugds/2CElnp3hvWM/fWI+rG6oZyRC+FGQwnEY4DgMEsu/dzK9RW7jjvTSyNzEfhKJrKQhuBcmL7LJdhn7UKCmMl7LlIXAK24ipmLzgBW2pRL9ldPpIL2RzCimptdQjGbtzILKhTaAxn1U9MA0WuuEtrZbeEVWZo9HfE0BMtyIoPLHAhTyvaQVLiaUx8J7EDjyYv0lOhJiBhquGnV8/z545AxBsTfokc2I90FUcdD4z5e0cVt2lrcg4zqgYCZ+bLfhfc+G6nkaa3Gj4oFbpUzuKbefWuJrEBujO3YA3PhtpKpGNoiSXUOm9bnG+Ky6SIVdnI/eF8ibSqnFWGvI/fCryHE94PxQvDdVA0GI0e4WFrIuiJRRweRsP3NuUJ+IYxMJDKdb0PDKDoaRBqeDMr/PQavQ/sFgIwkW+QW6do4uwMbS1RpqKdW7dJNO7Pk8IjraGUKfCqrbucMQMLlfo+q6PDYrMlX3YldL23SjC09Dmqg=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
